<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfPEoiv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfPEoiv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfPEoiv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfPEoiv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfPEoiv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfPEoiv',
    'container.build_id' => 'b2b402c9',
    'container.build_time' => 1597671780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfPEoiv');
